baseurl = "https://docs.fluidplayer.com/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Fluid Player Documentation"
theme = "hugo-material-docs-custom"

disqusShortname = ""
googleAnalytics = ""

publishDir = "docs"

[menu]
    [[menu.main]]
    identifier = "overview"
    name       = "Overview"
    url        = ""
    weight     = 1

    [[menu.main]]
    identifier = "integration"
    name       = "Integration"
    url        = "integration/"
    weight     = 2

    [[menu.main]]
    identifier = "builder"
    name       = "Builder"
    url        = "builder/"
    weight     = 3

    [[menu.main]]
    identifier = "layout_configuration"
    name       = "Layout Configuration"
    url        = "layout_configuration/"
    weight     = 4

    [[menu.main]]
    identifier = "ad_configuration"
    name       = "Ad Configuration"
    url        = "ad_configuration/"
    weight     = 5

    [[menu.main]]
    identifier = "preview_configuration"
    name       = "Preview Configuration"
    url        = "preview_configuration/"
    weight     = 6

    [[menu.main]]
    identifier = "api"
    name       = "API"
    url        = "api/"
    weight     = 7

    [[menu.main]]
    identifier = "streaming"
    name       = "Streaming"
    url        = "streaming/"
    weight     = 8

    [[menu.main]]
    identifier = "wordpress"
    name       = "Wordpress"
    url        = "wordpress/"
    weight     = 9

    [[menu.main]]
    identifier = "demo"
    name       = "Demo"
    url        = "demo/"
    weight     = 10

    [[menu.main]]
    identifier = "changelog"
    name       = "Changelog"
    url        = "changelog/"
    weight     = 11

    [[menu.main]]
    identifier = "help"
    name       = "Help"
    url        = "help/"
    weight     = 12

[params]
	highlightjs = "css/highlight.css"
	favicon = "favicon.png"

    logo = "fluid-logo.svg"
    version = "2.0.0"

[params.palette]
    primary = "light-blue"
    accent  = "light-blue"
